Update cross.yml

diff --git a/.github/workflows/cross.yml b/.github/workflows/cross.yml
--- a/.github/workflows/cross.yml
+++ b/.github/workflows/cross.yml
@@ -15,7 +15,8 @@ jobs:
           autoconf automake build-essential cmake \
           git libtool pkg-config texinfo \
           yasm nasm curl unzip wget \
-          mingw-w64 mingw-w64-x86-64-dev ninja-build zlib1g-dev libssl-dev
+          mingw-w64 mingw-w64-x86-64-dev ninja-build zlib1g-dev libssl-dev \
+          python3 python3-pip xz-utils
 
     - name: Set env vars
       run: |
@@ -87,18 +88,31 @@ jobs:
 
         # libvpx
         git clone --depth=1 https://chromium.googlesource.com/webm/libvpx.git && cd libvpx
-        ./configure --target=x86_64-win64-gcc --prefix=$PREFIX --disable-examples --disable-unit-tests --enable-vp9-highbitdepth --as=yasm --enable-static --disable-shared
+        ./configure \
+          --target=x86_64-win64-gcc \
+          --prefix=$PREFIX \
+          --disable-examples \
+          --disable-unit-tests \
+          --disable-tools \
+          --disable-docs \
+          --enable-vp8 \
+          --enable-vp9 \
+          --enable-vp9-highbitdepth \
+          --enable-static \
+          --disable-shared \
+          --as=yasm
         make -j$(nproc) && make install
         cd ..
 
         # libzlib
-        curl -LO https://zlib.net/zlib1213.zip
-        unzip zlib1213.zip && cd zlib-1.2.13
+        wget https://github.com/madler/zlib/releases/download/v1.3.1/zlib-1.3.1.tar.gz
+        tar xzf zlib-1.3.1.tar.gz && cd zlib-1.3.1
         CROSS_PREFIX=$CROSS_PREFIX \
         CC=${CROSS_PREFIX}-gcc AR=${CROSS_PREFIX}-ar RANLIB=${CROSS_PREFIX}-ranlib \
         ./configure --prefix=$PREFIX --static
         make
         make install
+        cd ..
 
         # freetype2
         git clone https://gitlab.freedesktop.org/freetype/freetype.git
@@ -122,6 +136,20 @@ jobs:
         make -j$(nproc) && make install
         cd ..
 
+        # fribidi (required by libass)
+        wget https://github.com/fribidi/fribidi/releases/download/v1.0.13/fribidi-1.0.13.tar.xz
+        tar xf fribidi-1.0.13.tar.xz && cd fribidi-1.0.13
+        ./configure --host=$CROSS_PREFIX --prefix=$PREFIX --disable-shared --enable-static --disable-docs
+        make -j$(nproc) && make install
+        cd ..
+
+        # harfbuzz (required by libass)
+        wget https://github.com/harfbuzz/harfbuzz/releases/download/8.3.0/harfbuzz-8.3.0.tar.xz
+        tar xf harfbuzz-8.3.0.tar.xz && cd harfbuzz-8.3.0
+        ./configure --host=$CROSS_PREFIX --prefix=$PREFIX --disable-shared --enable-static --with-freetype --with-glib=no --with-gobject=no --with-cairo=no --with-fontconfig=no --with-icu=no
+        make -j$(nproc) && make install
+        cd ..
+
         # libass
         git clone --depth=1 https://github.com/libass/libass.git && cd libass
         ./autogen.sh
@@ -140,12 +168,21 @@ jobs:
       run: |
         git clone --depth=1 https://github.com/FFmpeg/FFmpeg ffmpeg && cd ffmpeg
         export PKG_CONFIG_PATH=${{ env.PREFIX }}/lib/pkgconfig
+        export LDFLAGS="-L${{ env.PREFIX }}/lib"
+        export CPPFLAGS="-I${{ env.PREFIX }}/include"
+        
+        # Debug: Check if libvpx was installed correctly
+        ls -la ${{ env.PREFIX }}/lib/libvpx*
+        ls -la ${{ env.PREFIX }}/lib/pkgconfig/vpx.pc || echo "vpx.pc not found"
+        pkg-config --exists --print-errors vpx && echo "vpx pkg-config OK" || echo "vpx pkg-config FAILED"
+        
         ./configure \
           --target-os=mingw32 \
           --arch=x86_64 \
           --cross-prefix=${{ env.CROSS_PREFIX }}- \
           --prefix=${{ env.PREFIX }} \
           --pkg-config=pkg-config \
+          --pkg-config-flags="--static" \
           --enable-static --disable-shared \
           --enable-gpl --enable-version3 --enable-nonfree \
           --enable-libx264 --enable-libx265 \
@@ -154,6 +191,8 @@ jobs:
           --enable-libvpx \
           --enable-libopus --enable-libass \
           --enable-libaom --enable-nvenc \
+          --extra-cflags="-I${{ env.PREFIX }}/include" \
+          --extra-ldflags="-L${{ env.PREFIX }}/lib" \
           --disable-doc --disable-debug
         make -j$(nproc)
         make install
