Update native.yml

diff --git a/.github/workflows/native.yml b/.github/workflows/native.yml
--- a/.github/workflows/native.yml
+++ b/.github/workflows/native.yml
@@ -57,9 +57,10 @@ jobs:
       run: |
         git clone --branch stable --depth=1 https://bitbucket.org/multicoreware/x265_git x265
         cd x265/build/linux
+    
         # 修補 CMakeLists.txt 以支援新版 CMake
         sed -i 's/cmake_minimum_required(VERSION 2.8.8)/cmake_minimum_required(VERSION 3.5)/' ../../source/CMakeLists.txt
-        
+    
         cmake -G "Ninja" \
           -DCMAKE_BUILD_TYPE=Release \
           -DCMAKE_INSTALL_PREFIX=$PREFIX \
@@ -67,7 +68,16 @@ jobs:
           -DENABLE_CLI=OFF \
           -DENABLE_TESTS=OFF \
           -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
-          ../../source
+          ../../source || (
+            echo -e "\n===== CMakeOutput.log ====="
+            cat ../../build/CMakeFiles/CMakeOutput.log || echo "CMakeOutput.log not found."
+    
+            echo -e "\n===== CMakeError.log ====="
+            cat ../../build/CMakeFiles/CMakeError.log || echo "CMakeError.log not found."
+    
+            exit 1
+          )
+    
         ninja
         ninja install
         cd ../../../
